adding postgres and pgadmin dockerfile
esoviscode/database pull request #3
Opened 2022-12-15 19:48 UTC by kapselccc

…nd pgadmin4

2022-12-15 23:58 UTC, Silentsky0 requested changes

2022-12-15 23:58 UTC, Silentsky0 commented on README.md
> +localhost:5555
ten URL nie działa, raczej powinien być taki:
```suggestion
http://localhost:5555
```

2022-12-15 23:58 UTC, Silentsky0 commented on README.md
> +You can find it typing docker inspect (id of docker conatiner) in the Terminal, as a field IPAddress. Go to connection tab and insetr
dokumenty zawijamy do 80 znaków

2022-12-15 23:58 UTC, Silentsky0 commented on README.md
> +You can find it typing docker inspect (id of docker conatiner) in the Terminal, as a field IPAddress. Go to connection tab and insetr
```suggestion
You can find it by typing `docker inspect <id of docker container>` in the Terminal, as a field IPAddress. Go to connection tab and insert
```

2022-12-15 23:58 UTC, pcichowski commented on README.md
> +You can find it typing docker inspect (id of docker conatiner) in the Terminal, as a field IPAddress. Go to connection tab and insetr
Dodatkowo w README tego repozytorium jest komenda, która daje właśnie IP korzystając z inspecta

2022-12-15 23:58 UTC, Silentsky0 commented on docker-compose.yml
> +    container_name: postgres
niech zostanie postgresovisco
```suggestion
    container_name: postgresovisco
```

2022-12-15 23:58 UTC, Silentsky0 requested changes
@kapselccc w tym PR nie możemy usuwać istniejącego README

2022-12-16 13:54 UTC, kapselccc commented on README.md
> +localhost:5555
Normalnie u mnie działa

2022-12-16 13:54 UTC, kapselccc commented on README.md
> +localhost:5555
Ale może być i tak

2022-12-16 13:56 UTC, kapselccc commented
> @kapselccc w tym PR nie możemy usuwać istniejącego README

Ale tamto jest nieaktualne bo zmieniono całkowicie poprzednie rozwiązanie

2022-12-17 15:54 UTC, Silentsky0 commented on README.md
> +You can find it by typing `docker inspect <id of docker container>` in the
To było wcześniej w readme, myślę że to lepsza metoda na znalezienie adresu IP bazy
```suggestion
You can find it by typing `docker inspect  -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgresovisco`
```

2022-12-17 15:54 UTC, Silentsky0 commented on README.md
> +You can find it by typing `docker inspect <id of docker container>` in the
@kapselccc

2022-12-19 10:08 UTC, Silentsky0 commented
@kapselccc zmergowanie nie działa, przeanalizuj commity i zrób rebase, tak aby było poprawnie

2022-12-19 20:59 UTC, Silentsky0 approved these changes

2022-12-19 21:01 UTC, merged